name: uniride_app
description: "A new Flutter project."
publish_to: none

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  # OpenStreetMap
  flutter_map: ^7.0.0
  latlong2: ^0.9.0

  # Firebase packages 
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

  # Location package
  geolocator: ^10.0.0

  # Autocomplete / HTTP requests
  http: ^1.2.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/uniride_logo.jpg
